package inf.ufg.projeto_final_persistencia.entities;

import jakarta.persistence.Embeddable;
import lombok.*;

import java.io.Serializable;

@Embeddable
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UsuarioFavoritoId implements Serializable {
    private Long usuarioId;
    private Long pontoId;

    // equals/hashCode generated by Lombok (@Data) — fine for EmbeddedId
}
